### ISSUE TITLE
About “dataprocess.py”

### ISSUE THREAD

**Issue by Heroandzhang** [yanghan-yh/UGS-Net#5]
![image](https://github.com/yanghan-yh/UGS-Net/assets/51253044/07dbeca2-4ab3-432d-9d2e-58295f68211c)
关于训练的数据想要请教大家

1.  其中imagename我理解的是肺部图像，示例图如下，请问是否正确？：

![LIDC-IDRI-0003_2_3000611](https://github.com/yanghan-yh/UGS-Net/assets/51253044/b14b8a8f-70ca-40a1-98b4-b3b5bcd321bb)

2. 
-       innertemp0 = config.midPath + one_train_data + '.npy'  #self.midPath = './data/mid_image_npy/'
-       innertemp1 = config.lungPath + one_train_data + '_lung.npy'   #self.lungPath = './data/lung_image/'
-       innertemp2 = config.mediaPath + one_train_data + '_mediastinal.npy' # self.mediaPath = './data/media_image/
-       innertemp5 = config.maskPath1 + 'mid_' + one_train_data + '_mask.png'
- 中的以下路径分别包含哪些图像？
-      self.midPath = './data/mid_image_npy/'
-      self.lungPath = './data/lung_image/'
-      self.mediaPath = './data/media_image/'
-      self.maskPath1 = './data/row_image/'

3. 
- 我能理解innertemp3 = config.maskPath2 + one_train_data + '_red.png' # self.maskPath2 = './data/mid_image/'
-                 innertemp4 = config.maskPath2 + one_train_data + '_blue.png'
- 中的 innertemp3读取的是mask的并集，innertemp4读取的是mask的交集，请问是否正确呢？

**Comment by Maiyaww** [comment]
你好，我也有类似的疑惑，请问你知道以下几个路径对应的是什么图像吗？self.maskPath1 = './data/row_image/' # 对比实验所用数据集
        self.csvPath = './dataprocess/split_csv/' # fold_csv 
        self.maskPath2 = './data/mid_image/'
        self.midPath = './data/mid_image_npy/'
        self.lungPath = './data/lung_image/'
        self.mediaPath = './data/media_image/'
        self.figurePath = './result/figure/'
